{{ if .Values.schema.enabled }}
{{- range .Values.schema.jobs }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $.Values.component_name }}-{{ . }}
spec:
  template:
    spec:
      containers:
      - name: schema-load
        image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
        env:
          - name: SCHEMA_FILE
            value: db/{{ . }}.{{ $.Values.schema.extention }}
        {{- with $.Values.schema.env }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
      restartPolicy: Never
  backoffLimit: 4
{{- end }}
{{ end }}
