apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: {{ .Values.component_name }}
spec:
  mtls:
    mode: PERMISSIVE
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: {{ .Values.component_name }}-deny
spec: {}
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: {{ .Values.component_name }}-allow
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals: {{ .Values.istio.principals }}



